source ~/.zsh/checks.zsh
source ~/.zsh/colors.zsh
source ~/.zsh/setopt.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/bindkeys.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/history.zsh
source ~/.zsh/zsh_hooks.zsh
#source ~/.zsh/hitch.zsh
# source /opt/github/env.sh
source  ${HOME}/Documents/dotfiles/z/z.sh

#THIS MUST BE AT THE END OF THE FILE FOR JENV TO WORK!!!
[[ -s "/Users/Caixiaopig/.jenv/bin/jenv-init.sh" ]] && source "/Users/Caixiaopig/.jenv/bin/jenv-init.sh" && source "/Users/Caixiaopig/.jenv/commands/completion.sh"